apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ingress-nginx
  namespace: argocd
spec: 
  destination: 
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    helm:
      values: |
        controller:
          ingressClassResource:
            name: nginx-demo

    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.1
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
